export const teams = [
  {
    id: 1,
    name: 'Operations Team',
    thumbnail:
      'https://images.unsplash.com/photo-1588774210246-a1dc467758df?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80',
    members: [],
  },
  {
    id: 2,
    thumbnail:
      'https://images.unsplash.com/photo-1511089237-39fe21a69b7d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80',
    name: 'Marketing Team',
    members: [],
  },
  {
    id: 3,
    thumbnail:
      'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
    name: 'Franchise Managers',
    members: [],
  },
  {
    id: 'UNGROUPED',
    thumbnail:
      'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
    name: 'UNGROUPED',
    members: [],
  },
];

export const users = [
  {
    id: 1,
    name: 'Uma Myers',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/51.jpg',
    teamIds: null,
    role: 'Manager',
  },
  {
    id: 2,
    name: 'Imogen Gardner',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/52.jpg',
    teamIds: null,
    role: 'Franchise Manager',
  },
  {
    id: 3,
    name: 'Aayat Burke',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/53.jpg',
    teamIds: null,
    role: 'Manager',
  },
  {
    id: 4,
    name: 'Aminah Mckenzie',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/54.jpg',
    teamIds: null,
    role: 'Manager',
  },
  {
    id: 5,
    name: 'Carmel Pham',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/55.jpg',
    teamIds: null,
    role: 'Manager',
  },
  {
    id: 6,
    name: 'Jocelyn Graves',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/56.jpg',
    teamIds: null,
    role: 'Another Manager',
  },
  {
    id: 7,
    name: 'Walter Craf',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/57.jpg',
    teamIds: null,
    role: 'Manager',
  },
  {
    id: 8,
    name: 'Mandy Workman',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/58.jpg',
    teamIds: [1],
    role: 'Organization Manager',
  },
  {
    id: 9,
    name: 'Lubna Silva',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/59.jpg',
    teamIds: [1, 3],
    role: 'Manager',
  },
  {
    id: 10,
    name: 'Chardonnay Nguyen',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/60.jpg',
    teamIds: [1],
    role: 'Team Manager',
  },
  {
    id: 12,
    name: 'Zaine Boone',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/62.jpg',
    teamIds: [1],
    role: 'Manager',
  },
  {
    id: 13,
    name: 'Alysha Clemons',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/63.jpg',
    teamIds: [1, 2],
    role: 'Manager',
  },
  {
    id: 14,
    name: 'Connor Huffman',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/64.jpg',
    teamIds: [1, 2],
    role: 'General Manager',
  },
  {
    id: 15,
    name: 'Ivor Lopez',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/65.jpg',
    teamIds: [1, 3],
    role: 'Manager',
  },
  {
    id: 16,
    name: 'Raveena Mcclain',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/66.jpg',
    teamIds: [1, 2, 3],
    role: 'Manager',
  },
  {
    id: 17,
    name: 'Subhaan Ashton',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/67.jpg',
    teamIds: [2],
    role: 'Manager',
  },
  {
    id: 18,
    name: 'Jovan Jeffery',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/68.jpg',
    teamIds: [2, 3],
    role: 'Techlead',
  },
  {
    id: 19,
    name: 'Jasleen Davenport',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/69.jpg',
    teamIds: [2],
    role: 'Manager',
  },
  {
    id: 20,
    name: 'Cecilia Holden',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/71.jpg',
    teamIds: [2],
    role: 'Manager',
  },
  {
    id: 21,
    name: 'Yasmine Gough',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/72.jpg',
    teamIds: [2],
    role: 'Manager',
  },
  {
    id: 22,
    name: 'Findlay Needham',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/73.jpg',
    teamIds: [2],
    role: 'Techlead',
  },
  {
    id: 23,
    name: 'Jaheim Wolf',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/74.jpg',
    teamIds: [2, 3],
    role: 'Manager',
  },
  {
    id: 27,
    name: 'Randall Fox',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/78.jpg',
    teamIds: [3],
    role: 'Manager',
  },
  {
    id: 30,
    name: 'Samson Zuniga',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/80.jpg',
    teamIds: [3],
    role: 'Manager',
  },
  {
    id: 31,
    name: 'Adam Redmond',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/81.jpg',
    teamIds: [3],
    role: 'Manager',
  },
  {
    id: 32,
    name: 'Stanislaw Mejia',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/82.jpg',
    teamIds: [3],
    role: 'Manager',
  },
  {
    id: 33,
    name: 'Ayat Villa',
    thumbnail: 'https://randomuser.me/api/portraits/thumb/men/83.jpg',
    teamIds: [3],
    role: 'Manager',
  },
];
